#!/usr/bin/env bash
function _ssl2csv {
	data="$(head -n -1 "$1" | dos2unix | grep 'AD' | cut -d= -f2 | cut -d, -f1)"
	interval=$(($(head -n -1 "$1" | dos2unix | grep 'Interval' | cut -d= -f2)/10000000))
	cumint=0

	for datapoint in $data
	do
		echo $datapoint,$cumint
		cumint=$(($cumint + $interval))
	done
}
_ssl2csv "$1" > "$2"
